project_id: '530022'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:

# JSON translation files

- source: /i18n/en/**/\*
  translation: /i18n/%osx_locale%/**/%original_file_name%

# Docs Markdown files

- source: /docs/**/\*
  translation: /i18n/%osx_locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
